### ISSUE TITLE
No USERNAME in environment variables.

### ISSUE THREAD

**Issue by cloudy-sfu** [cloudy-sfu/GUI-for-tesseract-OCR#1]
Traceback (most recent call last):
  File "main.pyw", line 157, in <module>
  File "main.pyw", line 38, in __init__
  File "main.pyw", line 19, in get_ocr_path
  File "os.py", line 679, in __getitem__
KeyError: 'USERNAME'

**Comment by cloudy-sfu** [comment]
Source code changed, but haven't complied for release.

**Comment by cloudy-sfu** [comment]
Solved.
